### ISSUE TITLE
at_icon()

### ISSUE THREAD

**Issue by and1truong** [atdrupal/at_base.module#172]
Provide a simple function for developer to render icon.
- `at_icon($name, $source)`
- Support fontawesome
- Support fontello
- Provide `drush fontello` to build fontello
- Two unit-test cases, one for fontawesome, one for fontello
### Ref
- https://github.com/v3knet/at_base/blob/route-editable/at_base.module#L227
- https://github.com/v3knet/at_base/blob/route-editable/config/require.yml#L30

**Comment by tienvx** [comment]
![icons](https://f.cloud.github.com/assets/3327643/2393100/35ed2f50-a988-11e3-9066-37b50cec2084.png)

First preview.

**Comment by and1truong** [comment]
:+1:

**Comment by tienvx** [comment]
![icon](https://f.cloud.github.com/assets/3327643/2396281/a932f370-a9d6-11e3-8bad-cbe1ff83ea00.png)

Can use any icon from fontello.

**Comment by and1truong** [comment]
:+1:

**Comment by and1truong** [comment]
Follow #176
