### ISSUE TITLE
Error when install jquery update module 

### ISSUE THREAD

**Issue by phuong-bui-88** [atdrupal/at_base.module#177]
Uncaught Error: Syntax error, unrecognized expression: [value=at_base-gg_phuongbui|gg_search_form]
![error_jquery_update](https://f.cloud.github.com/assets/1611646/2417884/55a3d84c-ab2e-11e3-8e4d-14e3ffce8da9.png)

**Comment by phuong-bui-88** [comment]
Change from at_base-gg_phuongbui|gg_search_form to at_base-gg_phuongbui--gg_search_form. Do not have error.
![v15](https://f.cloud.github.com/assets/1611646/2417907/35dad6d6-ab2f-11e3-8391-da8a84223ef3.png)

**Comment by and1truong** [comment]
Can give me more information? Where do you define gg_phuong?

**Comment by phuong-bui-88** [comment]
Display when i used with context module. Path: admin/structure/context/list/global/edit
![v16](https://f.cloud.github.com/assets/1611646/2418457/22001f0e-ab43-11e3-8896-4f7553b0990f.png)

**Comment by tienvx** [comment]
Please patch module context by this patch
https://drupal.org/node/1272582
